# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    commandbus:
        default:
            middleware:
                - ThatBook\Middleware\ReleaseRecordedEventsMiddleware
                - tactician.middleware.locking
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler
