Mutation:
    type: object
    config:
        fields:
            registerReaderBook:
                type: Boolean
                args:
                    bookId:
                        type: String!
                    readerId:
                        type: String!                        
                resolve: >
                    @=service("tactician.commandbus.default")
                        .handle(
                            newObject("ThatBook\\Service\\RegisterReaderBook", [
                                args["bookId"],
                                args["readerId"]
                            ])
                        )

            registerReaderWish:
                type: Boolean
                args:
                    bookId:
                        type: String!
                    readerId:
                        type: String!                        
                resolve: >
                    @=service("tactician.commandbus.default")
                        .handle(
                            newObject("ThatBook\\Service\\RegisterReaderWish", [
                                args["bookId"],
                                args["readerId"]
                            ])
                        )

            catalogBook:
                type: Boolean
                args:
                    title:
                        type: String!
                    publisher:
                        type: String
                    category:
                        type: ID!
                resolve: >
                    @=service("tactician.commandbus.default")
                        .handle(
                            newObject("ThatBook\\Service\\CatalogBook", [
                                args["title"],
                                args["publisher"],
                                args["category"]
                            ])
                        )

            registerReader:
                type: Boolean
                args:
                    name:
                        type: String!
                resolve: >
                    @=service("tactician.commandbus.default")
                        .handle(
                            newObject("ThatBook\\Service\\RegisterReader", [
                                args["name"]
                            ])
                        )