Query:
    type: object
    config:
        fields:
            books:
                type: "[Book]"
                resolve: '@=service("ThatBook\\Repository\\BookRepository").findAll()'
            readers:
                type: "[Reader]"
                resolve: '@=service("ThatBook\\Repository\\ReaderRepository").findAll()'
